repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        stages: [commit]
        pass_filenames: true
        args: ['--config-file=pyproject.toml']
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        stages: [commit]
        pass_filenames: true
        args: ['--config=pyproject.toml']
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        stages: [commit]
        require_serial: false
        pass_filenames: true